# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skillex < Formula
  desc "TUI for browsing and reading installed Claude Code skills"
  homepage "https://github.com/smauermann/skillex"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/smauermann/skillex/releases/download/v0.5.0/skillex_0.5.0_darwin_amd64.tar.gz"
      sha256 "d0ee342c8a770f6b717e74ea7e212e518b3d8457378aa65ad12744228f483198"

      define_method(:install) do
        bin.install "skillex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/smauermann/skillex/releases/download/v0.5.0/skillex_0.5.0_darwin_arm64.tar.gz"
      sha256 "706903340483af27d257b87f5b43e61cb06d35fd2955981be543a2bd1b1fea24"

      define_method(:install) do
        bin.install "skillex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/smauermann/skillex/releases/download/v0.5.0/skillex_0.5.0_linux_amd64.tar.gz"
      sha256 "26f7c2fdbc9bb1e1729e98a23fb040d353095f2cb818c10a0d82b2de3d66d397"
      define_method(:install) do
        bin.install "skillex"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/smauermann/skillex/releases/download/v0.5.0/skillex_0.5.0_linux_arm64.tar.gz"
      sha256 "ed28354868a7013250e0aee97d919750ea6edc6e183c96ee95bad614c40c5f7e"
      define_method(:install) do
        bin.install "skillex"
      end
    end
  end

  test do
    assert_match "Error discovering skills", shell_output("#{bin}/skillex 2>&1", 1)
  end
end
